"""initial migration

Revision ID: 19d7e94c49a3
Revises: None
Create Date: 2015-05-10 13:47:03.280000

"""

# revision identifiers, used by Alembic.
revision = '19d7e94c49a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
